### ISSUE TITLE
Cockpit sometimes fails to load

### ISSUE THREAD

**Issue by manugarciac** [camunda/camunda-cockpit-plugin-statistics#11]
Sometimes the Cockpit fails to load and this is the error that is thrown:

ReferenceError: d3 is not defined	
var formatHours = d3.time.format("%H:%M");

In the following file: .../api/cockpit/plugin/statistics-plugin/static/app/directives/spRegressionPlot.js

If I keep hitting F5 it loads. It seems random. Maybe some kind of race condition?

**Comment by eklieme** [comment]
hi manu,

I am already working on it :)

**Comment by eklieme** [comment]
please give it a try now

**Comment by manugarciac** [comment]
So far so good. I'll let you know if I find anything else.

A suggestion though. It would be awesome if you updated the POM version whenever you commit to master. As the version is still 1.0.0, I had to overwrite the previous jar, instead of just uploading a new one and updating my POM.

**Comment by eklieme** [comment]
all right :)
