### ISSUE TITLE
Details on Process Definition - Not always being displayed

### ISSUE THREAD

**Issue by KlassikNoise46** [camunda/camunda-cockpit-plugin-statistics#12]
Hi,

I've been using the plug in for a little while now and noticed that from the Cockpit Start screen, when selecting a deployed process by clicking on the coloured bars, this doesn't always result in the graphical / statistical process versions pop-up being displayed.

The process in question is the approve-loan process, which I built by following the BPMN getting started guides on Camunda.org. I'm thinking perhaps I've missed something fundamental.

I've deployed the plug in jar to my tomcat server and all seems well apart from this feature on this process. I wondered what the criteria is to activate this feature.

Regards,
Ian

**Comment by eklieme** [comment]
Hi Ian,

sorry for the late response..I do not know why I was not notified..nevermind. Can you give further details of your setup? Like the number of running/finished processes / task? In addition you could open your browser web developer tools with F12 or Strg+Shift+I (Chrome) and have a look at the 'console' tab while trying to activate that feature. I will have a look at it as soon as possible afterwards :)

cheers,
Eric

**Comment by KlassikNoise46** [comment]
Hi Eric,

Using the developer tools in Chrome, I get the following error when I click on the loan-approval process bar:

TypeError: Cannot read property '0' of undefined
    at processesChartCtrl.js?bust=7.6.0:488
    at wrappedCallback (deps.js?bust=7.6.0:42307)
    at wrappedCallback (deps.js?bust=7.6.0:42307)
    at wrappedCallback (deps.js?bust=7.6.0:42307)
    at deps.js?bust=7.6.0:42393
    at Scope.$eval (deps.js?bust=7.6.0:43436)
    at Scope.$digest (deps.js?bust=7.6.0:43248)
    at Scope.$apply (deps.js?bust=7.6.0:43540)
    at done (deps.js?bust=7.6.0:39051)
    at completeRequest (deps.js?bust=7.6.0:39265)
(anonymous) @ deps.js?bust=7.6.0:40732
(anonymous) @ deps.js?bust=7.6.0:37999
wrappedCallback @ deps.js?bust=7.6.0:42310
wrappedCallback @ deps.js?bust=7.6.0:42307
wrappedCallback @ deps.js?bust=7.6.0:42307
(anonymous) @ deps.js?bust=7.6.0:42393
$eval @ deps.js?bust=7.6.0:43436
$digest @ deps.js?bust=7.6.0:43248
$apply @ deps.js?bust=7.6.0:43540
done @ deps.js?bust=7.6.0:39051
completeRequest @ deps.js?bust=7.6.0:39265
xhr.onreadystatechange @ deps.js?bust=7.6.0:39204

I'm using the Tomcat distribution from Camunda.org with the loan-approval process and statistics plugin. 

There are 1 running & 7 complete tasks for loan-approval, 5 running and 1 complete for the included invoice process. The version details appear for invoice process, just not for loan-approval.

Regards,
Ian.

**Comment by frameworkbattle** [comment]
Hi Ian,

Ok.. I ll take a look and get back to you asap.

cheers,
Eric

**Comment by eklieme** [comment]
Hi Ian,

Ok.. I ll take a look and get back to you asap.

cheers,
Eric

**Comment by eklieme** [comment]
Give it a try ;)
