### ISSUE TITLE
No Duration Tab

### ISSUE THREAD

**Issue by isaacueca** [camunda/camunda-cockpit-plugin-statistics#6]
Hi -

First of all, thanks for making this plugin available.

I deployed it on Camunda 7.3 but was unable to see the Duration tab. I'm not sure if I'm missing any steps..

Any help would be greatly appreciated

Thanks

Isaac

**Comment by berndruecker** [comment]
Hi Isaac. 

You have to build the plugin and copy the resulting jar into your cockpit war as decribed here: http://docs.camunda.org/7.3/real-life/how-to/#cockpit-how-to-develop-a-cockpit-plugin-integration-into-cockpit. Hope that helps.

Please point further questions to the forum. Thanks!

Cheers
Bernd

**Comment by isaacueca** [comment]
Hi Bernd, I had already done all the steps described in the Camunda documentation. 

My specific issue is that whatever I saw in the screenshots and description of the plugin is not what I got when I deployed it to Cockpit.

Looking at the source code for the plugin, I saw that the "Durations" tab was commented out from the HTML markup located in the dashboard.html under  /src/main/resources/plugin-webapp/statistics-plugin/dashboard.html. I uncommented that markup, re-deployed the plugin and got the Durations tab to show, but with no graph or content inside it.

In addition, the "Timings" and "Statistics" tabs do not seem to reflect the fields that we see in the screenshots of the documentation. 

My guess is that the plugin is still not ready for Camunda 7.3...

Thanks

Isaac

**Comment by eklieme** [comment]
Hi Isaac,

the plugin is ready for 7.3 but we are currently improving the duration tab due to some heavy refactoring. Sorry - I forgot to remove the respective screenshot :(

Do you have any special requirements concerning a 'durations' tab?

**Comment by isaacueca** [comment]
Hi Eric, 

Thanks for following up.

I don't have any specific requirements related to the "durations" tab. 

However, the idea of having min, max, avg duration for finished activities per process is an attractive one. If that could be categorized by users, it would be even better :)

I noticed that in the updated screenshots you have provided, there's indeed duration information for activities displayed in the pie chart. However, in my deployment using the latest commits from the master branch there's no such information about duration...

Best,
Isaac
