### ISSUE TITLE
How to build Jar

### ISSUE THREAD

**Issue by manugarciac** [camunda/camunda-cockpit-plugin-statistics#8]
Hello. I'm having trouble building the Jar. I checked out the project, and when I run maven clean package I get the following errors:

`
[ERROR] /home/mc/Desarrollo/git/camunda-cockpit-plugin-statistics/src/main/java/org/camunda/cockpit/plugin/statistics/resources/StatisticsPluginRootResource.java:[8,47] package org.camunda.bpm.engine.rest.sub.runtime does not exist
[ERROR] /home/mc/Desarrollo/git/camunda-cockpit-plugin-statistics/src/main/java/org/camunda/cockpit/plugin/statistics/resources/process/IncidentResource.java:[9,47] package org.camunda.bpm.engine.rest.dto.runtime does not exist
[ERROR] /home/mc/Desarrollo/git/camunda-cockpit-plugin-statistics/src/main/java/org/camunda/cockpit/plugin/statistics/resources/process/IncidentResource.java:[31,17] cannot find symbol
  symbol:   class IncidentDto
  location: class org.camunda.cockpit.plugin.statistics.resources.process.IncidentResource
[ERROR] /home/mc/Desarrollo/git/camunda-cockpit-plugin-statistics/src/main/java/org/camunda/cockpit/plugin/statistics/resources/process/IncidentResource.java:[33,37] cannot find symbol
  symbol:   class IncidentDto
  location: class org.camunda.cockpit.plugin.statistics.resources.process.IncidentResource
`

I also tried de Plugin store, but I get the following error there:

`Could not clone and build plugin: https://github.com/camunda/camunda-cockpit-plugin-statistics/blob/master/pom.xml`

With this root cause:

`java.lang.IllegalStateException: ${maven.home} is not specified as a directory: '/usr/share/maven-bin-3.0'.`

How can I build the Jar for this plugin?

**Comment by eklieme** [comment]
Hi manugarciac,

I just tried a 'green field' clone and successfully built the jar using maven clean package. Did you check out the master branch? Did you do anything before your build?

cheers,

Eric

**Comment by manugarciac** [comment]
The only thing I did manually was downloading this dependency: 

`org.camunda.bpm.webapp:camunda-webapp-core:jar:7.3.0`

Because when I don't, I get this error:

`
[ERROR] Failed to execute goal on project camunda-cockpit-plugin-statistics-root: Could not resolve dependencies for project org.camunda.bpm.extension:camunda-cockpit-plugin-statistics-root:jar:1.0.0: Failure to find org.camunda.bpm.webapp:camunda-webapp-core:jar:7.3.0 in http://repo.contentamobile.com.ar/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`

Any ideas? Maybe something different in my setting.xml? I added this:

`
  <profile>
    <id>camunda-bpm</id>
    <repositories>
      <repository>
        <id>camunda-bpm-nexus</id>
        <name>camunda-bpm-nexus</name>
        <releases>
          <enabled>true</enabled>
        </releases>
        <snapshots>
          <enabled>true</enabled>
        </snapshots>
        <url>https://app.camunda.com/nexus/content/groups/public</url>
      </repository>
    </repositories>
  </profile>
`

And this:

`
<activeProfiles>
  <activeProfile>camunda-bpm</activeProfile>
</activeProfiles>
`

**Comment by eklieme** [comment]
:) great

**Comment by shantanu-deriv** [comment]
Hi, I am using the same version of camunda as specified [7.6 tomcat distribution](https://downloads.camunda.cloud/release/camunda-bpm/tomcat/7.6/camunda-bpm-tomcat-7.6.0.zip) then I build this project with `mvn clean install` and copy the jar from `./target/camunda-cockpit-plugin-statistics-root-1.0.0.jar` to `lib` folder of above distribution zip. But I dont see the plugin when I start the server on cockpit dashboard. What am I doing wrong?
